// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6gOX6v_Y9KqqCcbJ00xiCqKBp2Pwj1xE',
    appId: '1:520853733983:web:f81449ecaef2c3a83951ea',
    messagingSenderId: '520853733983',
    projectId: 'chatapp-96df8',
    authDomain: 'chatapp-96df8.firebaseapp.com',
    storageBucket: 'chatapp-96df8.appspot.com',
    measurementId: 'G-YY7EJR2NGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMvnF9auB_HJGbq9B48Brx5hr_HlNZ75Q',
    appId: '1:520853733983:android:c45a741b4acb09753951ea',
    messagingSenderId: '520853733983',
    projectId: 'chatapp-96df8',
    storageBucket: 'chatapp-96df8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzLHaJMatkO-aw78J5QYhG3GezzPnQO9k',
    appId: '1:520853733983:ios:ce3f0d02dc6b0c973951ea',
    messagingSenderId: '520853733983',
    projectId: 'chatapp-96df8',
    storageBucket: 'chatapp-96df8.appspot.com',
    iosBundleId: 'com.example.meuChatOngUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzLHaJMatkO-aw78J5QYhG3GezzPnQO9k',
    appId: '1:520853733983:ios:1b2f02efe34e6ef33951ea',
    messagingSenderId: '520853733983',
    projectId: 'chatapp-96df8',
    storageBucket: 'chatapp-96df8.appspot.com',
    iosBundleId: 'com.example.meuChatOngUser.RunnerTests',
  );
}
